### ISSUE TITLE
Downloading OSO products?

### ISSUE THREAD

**Issue by Redcozmo** [remicres/theia-picker#7]
Hello Rémi,
Does the tool allow downloading OSO products?
Thanks
Josselin

**Comment by remicres** [comment]
Hi Josselin,

If OSO is in the same catalog, then it should be doable theoretically. However for now only S2 level 2 & 3 models are implemented, so would have to put your hands in the code to do that !

**Comment by Redcozmo** [comment]
Ok merci !! Je vais trouver une autre solution !

**Comment by Redcozmo** [comment]
Ok merci !! Je vais trouver une autre solution !
